export enum TASKS_ACTIONS {
    GET_TASKS = "GET_TASKS",
    ADD_TASKS = "ADD_TASKS",
    DELETE_TASKS = "DELETE_TASKS",
    EDIT_TASKS = "EDIT_TASKS",
}


export enum MEMBERS_ACTION {
    GET_MEMBERS= "GET_MEMBERS",
    ADD_MEMBERS = "ADD_MEMBERS",
    DELETE_MEMBERS = "DELETE_MEMBERS",
    EDIT_MEMBERS = "EDIT_MEMBERS",
}

